version: '3.8'

services:
  backend:
    build:
      context: ./ContactsBackend
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:5102
      - ASPNETCORE_Kestrel__Certificates__Default__Password=devpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./certs:/https:ro
    ports:
      - "5102:5102"
    networks:
      - contacts-net

  frontend:
    build:
      context: ./ContactsFrontend
      dockerfile: ./Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - contacts-net

networks:
  contacts-net:
    driver: bridge
